- ros_topic_name: '/clock'
  gz_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: GZ_TO_ROS

- ros_topic_name: '/joint_states'
  gz_topic_name: '/joint_states'
  ros_type_name: 'sensor_msgs/msg/JointState'
  gz_type_name: 'gz.msgs.Model'
  direction: GZ_TO_ROS

- ros_topic_name: '/cmd_pos/FL_hip_joint'
  gz_topic_name: '/cmd_pos/FL_hip_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_pos/FL_thigh_joint'
  gz_topic_name: '/cmd_pos/FL_thigh_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_pos/FL_calf_joint'
  gz_topic_name: '/cmd_pos/FL_calf_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_pos/FR_hip_joint'
  gz_topic_name: '/cmd_pos/FR_hip_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_pos/FR_thigh_joint'
  gz_topic_name: '/cmd_pos/FR_thigh_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_pos/FR_calf_joint'
  gz_topic_name: '/cmd_pos/FR_calf_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_pos/RL_hip_joint'
  gz_topic_name: '/cmd_pos/RL_hip_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_pos/RL_thigh_joint'
  gz_topic_name: '/cmd_pos/RL_thigh_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_pos/RL_calf_joint'
  gz_topic_name: '/cmd_pos/RL_calf_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_pos/RR_hip_joint'
  gz_topic_name: '/cmd_pos/RR_hip_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_pos/RR_thigh_joint'
  gz_topic_name: '/cmd_pos/RR_thigh_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_pos/RR_calf_joint'
  gz_topic_name: '/cmd_pos/RR_calf_joint'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ
- ros_topic_name: '/gz_tf'
  gz_topic_name: '/world/mini_cheetah_world/dynamic_pose/info'
  ros_type_name: 'tf2_msgs/msg/TFMessage'
  gz_type_name: 'gz.msgs.Pose_V'
  direction: GZ_TO_ROS

- ros_topic_name: '/odom_ground_truth'
  gz_topic_name: '/model/mini_cheetah/odometry'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name: 'gz.msgs.Odometry'
  direction: GZ_TO_ROS

- ros_topic_name: '/imu'
  gz_topic_name: '/imu'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name: 'gz.msgs.IMU'
  direction: GZ_TO_ROS

- ros_topic_name: '/contact/FL'
  gz_topic_name: '/contact/FL'
  ros_type_name: 'ros_gz_interfaces/msg/Contacts'
  gz_type_name: 'gz.msgs.Contacts'
  direction: GZ_TO_ROS

- ros_topic_name: '/contact/FR'
  gz_topic_name: '/contact/FR'
  ros_type_name: 'ros_gz_interfaces/msg/Contacts'
  gz_type_name: 'gz.msgs.Contacts'
  direction: GZ_TO_ROS

- ros_topic_name: '/contact/RL'
  gz_topic_name: '/contact/RL'
  ros_type_name: 'ros_gz_interfaces/msg/Contacts'
  gz_type_name: 'gz.msgs.Contacts'
  direction: GZ_TO_ROS

- ros_topic_name: '/contact/RR'
  gz_topic_name: '/contact/RR'
  ros_type_name: 'ros_gz_interfaces/msg/Contacts'
  gz_type_name: 'gz.msgs.Contacts'
  direction: GZ_TO_ROS


- ros_topic_name: '/imu'
  gz_topic_name: '/imu'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name: 'gz.msgs.IMU'
  direction: GZ_TO_ROS

- ros_topic_name: '/contact/FL'
  gz_topic_name: '/contact/FL'
  ros_type_name: 'ros_gz_interfaces/msg/Contacts'
  gz_type_name: 'gz.msgs.Contacts'
  direction: GZ_TO_ROS

- ros_topic_name: '/contact/FR'
  gz_topic_name: '/contact/FR'
  ros_type_name: 'ros_gz_interfaces/msg/Contacts'
  gz_type_name: 'gz.msgs.Contacts'
  direction: GZ_TO_ROS

- ros_topic_name: '/contact/RL'
  gz_topic_name: '/contact/RL'
  ros_type_name: 'ros_gz_interfaces/msg/Contacts'
  gz_type_name: 'gz.msgs.Contacts'
  direction: GZ_TO_ROS

- ros_topic_name: '/contact/RR'
  gz_topic_name: '/contact/RR'
  ros_type_name: 'ros_gz_interfaces/msg/Contacts'
  gz_type_name: 'gz.msgs.Contacts'
  direction: GZ_TO_ROS
