- ros_topic_name: '/clock'
  gz_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: GZ_TO_ROS

- ros_topic_name: '/joint_states'
  gz_topic_name: '/joint_states'
  ros_type_name: 'sensor_msgs/msg/JointState'
  gz_type_name: 'gz.msgs.Model'
  direction: GZ_TO_ROS

- ros_topic_name: '/cmd_effort/FL_hip_joint'
  gz_topic_name: '/model/mini_cheetah/joint/FL_hip_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_effort/FL_thigh_joint'
  gz_topic_name: '/model/mini_cheetah/joint/FL_thigh_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_effort/FL_calf_joint'
  gz_topic_name: '/model/mini_cheetah/joint/FL_calf_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_effort/FR_hip_joint'
  gz_topic_name: '/model/mini_cheetah/joint/FR_hip_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_effort/FR_thigh_joint'
  gz_topic_name: '/model/mini_cheetah/joint/FR_thigh_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_effort/FR_calf_joint'
  gz_topic_name: '/model/mini_cheetah/joint/FR_calf_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_effort/RL_hip_joint'
  gz_topic_name: '/model/mini_cheetah/joint/RL_hip_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_effort/RL_thigh_joint'
  gz_topic_name: '/model/mini_cheetah/joint/RL_thigh_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_effort/RL_calf_joint'
  gz_topic_name: '/model/mini_cheetah/joint/RL_calf_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_effort/RR_hip_joint'
  gz_topic_name: '/model/mini_cheetah/joint/RR_hip_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_effort/RR_thigh_joint'
  gz_topic_name: '/model/mini_cheetah/joint/RR_thigh_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ

- ros_topic_name: '/cmd_effort/RR_calf_joint'
  gz_topic_name: '/model/mini_cheetah/joint/RR_calf_joint/cmd_force'
  ros_type_name: 'std_msgs/msg/Float64'
  gz_type_name: 'gz.msgs.Double'
  direction: ROS_TO_GZ
- ros_topic_name: '/gz_tf'
  gz_topic_name: '/world/mini_cheetah_world/dynamic_pose/info'
  ros_type_name: 'tf2_msgs/msg/TFMessage'
  gz_type_name: 'gz.msgs.Pose_V'
  direction: GZ_TO_ROS

- ros_topic_name: '/odom_ground_truth'
  gz_topic_name: '/model/mini_cheetah/odometry'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name: 'gz.msgs.Odometry'
  direction: GZ_TO_ROS
